### ISSUE TITLE
Become owner

### ISSUE THREAD

**Issue by erkie** [SamvelRaja/google-maps-addon#16]
Hi,

I would love to help out with this repo and addon. What do you think about making me an owner/contributor as well so we can iterate quickly?

**Comment by SamvelRaja** [comment]
Thanks for the interest @erkie... I ll make it by this weekend

**Comment by SamvelRaja** [comment]
Yes, Definitely we can, just to stay on single context, we shall put our ideas as issue and achieve them over it.

I have made you as collaborator so that you can have the appropriate access to the repo.
