### ISSUE TITLE
Having the milestones for adding additional functionalities

### ISSUE THREAD

**Issue by SamvelRaja** [SamvelRaja/google-maps-addon#20]
@erkie  your thoughts?

**Comment by erkie** [comment]
Hmm, you mean creating a milestone for each feature? Isn't an issue enough?

**Comment by SamvelRaja** [comment]
I mean a milestone contains list of features

**Comment by erkie** [comment]
@SamvelRaja slow reply but I think this sounds like a good idea. :D
